[tool.poetry]
name = "scripts"
version = "0.0.1"
description = "any Python scripts needed!"
authors = ["Damien Chomat <damien.chomat@gmail.com>"]
readme = "README.md"
packages = [{include = "work-time-off"}]

[tool.poetry.dependencies]
python = ">=3.12"
holidays = "0.59"
slack-sdk = "3.33.1"