# uv run by_instance_type
[project]
name = "aws-cost-estimator"
version = "0.1.0"
description = "A script to estimate AWS costs using boto3."
requires-python = ">=3.13"
dependencies = [
    "boto3==1.35.63",
    "requests==2.32.3",
    "kubernetes==31.0.0",
    "argparse==1.4.0"
]

[project.scripts]
by_instance_type = "aws_cost_estimator.get_by_instance_type:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
by_instance_type = ["src/aws_cost_estimator"]

[tool.uv]
dev-dependencies = [
    "pyright>=1.1.389",
    "ruff>=0.7.1",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
