# uv run by_instance_type
[project]
name = "k8s-kube-ovn-ip-cleanup"
version = "0.1.0"
description = "A script to delete all IPs not belonging to an existing namespace."
requires-python = ">=3.13"
dependencies = [
    "kubernetes==31.0.0",
]

[project.scripts]
delete_kube_ovn_ip = "k8s_kube_ovn_ip_cleanup.delete_kube_ovn_ip:delete_ips_in_nonexistent_namespaces"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
delete_kube_ovn_ip = ["src/k8s_kube_ovn_ip_cleanup"]

[tool.uv]
dev-dependencies = [
    "pyright>=1.1.389",
    "ruff>=0.7.1",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
