name: 'Setup Python project'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.4

    - name: Install dependencies
      shell: bash
      run: poetry install
