name: "Setup Python project"

inputs:
  work-dir:
    description: "Path to Python Package"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - shell: bash
      run: cd ${{ inputs.work-dir }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install the project
      shell: bash
      run: uv sync --all-extras --dev
