# uv run generate_report
#
[project]
name = "worktimeoff"
version = "0.1.0"
description = "Weekly and monthly work time off reports."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "slack-sdk>=3.35.0",
]

[project.scripts]
generate_report = "worktimeoff.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
generate_report = ["src/worktimeoff"]

# Indicates to pytest where to find source code
[tool.pytest.ini_options]
pythonpath = ["src"]

# https://pytest-mock.readthedocs.io/en/latest/configuration.html#use-standalone-mock-package
[pytest]
mock_use_standalone_module = true

[tool.pyright]
venvPath = "."
venv = ".venv"
