name: Post to Slack Channel
on:
  workflow_dispatch:
  schedule:
    # Runs daily at 11:30 AM Eastern Time
    - cron: "30 16 * * *"

jobs:
  post-work-time-off:
    runs-on: ubuntu-latest
    environment: prod
    env:
      WORK_DIR: worktimeoff
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python

      - name: Post work time off
        env:
          SLACK_CHANNEL_ID: ${{ vars.PELOTECH_SLACK_CHANNEL_ID }}
          SLACK_USER_ID: ${{ vars.PELOTECH_SLACK_USER_ID }}
          SLACK_USER_TOKEN: ${{ secrets.PELOTECH_SLACK_USER_TOKEN }}
          CURRENT_CLIENT: ${{ vars.PELOTECH_CURRENT_CLIENT }}
        run: |
          uv run generate_report $CURRENT_CLIENT -c $SLACK_CHANNEL_ID -u $SLACK_USER_ID -t $SLACK_USER_TOKEN
