on:
  workflow_dispatch:
  schedule:
    # Runs at 11 AM PST every Thursday
    - cron: '0 19 * * 4'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4

      - name: Install dependencies
        run: poetry install

      - name: Run script
        env:
          PELOTECH_SLACK_USER_TOKEN: ${{ secrets.PELOTECH_SLACK_USER_TOKEN }}
        run: poetry run python work-time-off/main.py