name: Post to Slack Channel
on:
  workflow_dispatch:
  schedule:
    # Runs at 11 AM West Coast time every Thursday
    - cron: "0 17,18 * * 4"

jobs:
  check-run:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.check_local_time.outputs.run }}
    steps:
      - name: Check local time
        id: check_local_time
        env:
          TRIGGER: ${{ github.event_name }}
        run: |
          # GitHub issue: https://github.com/orgs/community/discussions/13454
          echo "Trigger: ${TRIGGER}"
          if [[ ${TRIGGER} == 'schedule' ]]; then
            echo "Checking daylight saving time"
            if [ $(TZ='America/Los_Angeles' date +%H) -eq '11' ]; then
              echo 'Time to run!'
              echo "run=true" >> "$GITHUB_OUTPUT"
            else
              echo "It's not 11:00 local time in America/Los_Angeles. Waiting for next execution..."
              echo "run=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo 'Trigger is not cron, omitting time check!'
            echo "run=true" >> "$GITHUB_OUTPUT"
          fi

  post-work-time-off:
    runs-on: ubuntu-latest
    needs: check-run
    if: ${{ needs.check-run.outputs.run == 'true' }}
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python

      - name: Post work time off
        env:
          SLACK_CHANNEL_ID: ${{ vars.PELOTECH_SLACK_CHANNEL_ID }}
          SLACK_USER_ID: ${{ vars.PELOTECH_SLACK_USER_ID }}
          SLACK_USER_TOKEN: ${{ secrets.PELOTECH_SLACK_USER_TOKEN }}
          CURRENT_CLIENT: ${{ vars.PELOTECH_CURRENT_CLIENT }}
        run: uv run worktimeoff $CURRENT_CLIENT -c $SLACK_CHANNEL_ID -u $SLACK_USER_ID -t $SLACK_USER_TOKEN
