name: Post work time off to 'automation' private channel
on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  post-work-time-off:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python

      - name: Test post work time off for Damien
        env:
          PELOTECH_SLACK_USER_TOKEN: ${{ secrets.PELOTECH_SLACK_USER_TOKEN }}
          SLACK_USER_ID: "U02AE3A63D2"
          CURRENT_CLIENT: "UKI"
          SLACK_CHANNEL_ID: "C05P1M9FGUS"
        run: poetry run python work-time-off/main.py $SLACK_CHANNEL_ID $SLACK_USER_ID $CURRENT_CLIENT
